### ISSUE TITLE
Bug: /modlog does nothing

### ISSUE THREAD

**Issue by TheMezStrikes** [XpRienzo/DragonHeaven#746]
No error message, no feedback, no reaction in any way

**Comment by TheMezStrikes** [comment]
I'll get on this one

**Comment by Spandamn** [comment]
It's a server bug which not even @xprienzo knows how to fix

**Comment by XpRienzo** [comment]
/modlog has been fixed, restoring the directories fixed it. Too bad the logs have been lost. /roomban on the other hand has not.
